SET SEARCH_PATH = "public";

-- Popular Despesas
INSERT INTO DESPESAS (DESCRICAO, VALOR, DATA, CATEGORIA) VALUES ('Aluguel', 1200.00, '2022-10-15', 'MORADIA');
INSERT INTO DESPESAS (DESCRICAO, VALOR, DATA, CATEGORIA) VALUES ('Energia', 120.00, '2022-10-05', 'MORADIA');
INSERT INTO DESPESAS (DESCRICAO, VALOR, DATA, CATEGORIA) VALUES ('Água', 600.00, '2022-10-05', 'MORADIA');
-- Popular Receitas
INSERT INTO RECEITAS (DESCRICAO, VALOR, DATA) VALUES ('Adiantamento', 2800.00, '2022-10-15');
INSERT INTO RECEITAS (DESCRICAO, VALOR, DATA) VALUES ('Salário', 2500.00, '2022-10-30');
-- Popular Perfil
INSERT INTO PERFIS (NOME) VALUES ('ADMIN');
INSERT INTO PERFIS (NOME) VALUES ('USER');
-- Popular Usuarios
INSERT INTO USUARIOS (NOME, EMAIL, SENHA) VALUES ('Kaique de Miranda', 'kbdemiranda@hotmail.com', '$2a$10$OSKDZhGdVI/PnfilIsVaEONBXYpUhEun1k5sQiHqs7RUVJQpmCjPq');
INSERT INTO USUARIOS_PERFIS(USUARIOS_ID, PERFIS_ID) VALUES (1,1);
