CREATE TABLE RECEITAS(
    ID BIGSERIAL,
    DESCRICAO VARCHAR(255),
    VALOR DECIMAL(10,2),
    DATA DATE,

    CONSTRAINT PK_RECEITAS PRIMARY KEY (ID)
);

INSERT INTO RECEITAS (DESCRICAO, VALOR, DATA) VALUES ('Adiantamento', 2800.00, '2022-10-15');
INSERT INTO RECEITAS (DESCRICAO, VALOR, DATA) VALUES ('Salário', 2500.00, '2022-10-30');