CREATE TABLE PERFIS(
     ID BIGSERIAL,
     NOME VARCHAR(255) NOT NULL,

     CONSTRAINT PK_PERFIS PRIMARY KEY (ID)
);

INSERT INTO PERFIS (NOME) VALUES ('ADMIN');
INSERT INTO PERFIS (NOME) VALUES ('USER');