CREATE TABLE USUARIOS_PERFIS(
     USUARIOS_ID INTEGER NOT NULL,
     PERFIS_ID INTEGER NOT NULL,


     CONSTRAINT FK_USUARIOS FOREIGN KEY (USUARIOS_ID) REFERENCES USUARIOS (ID),
     CONSTRAINT FK_PERFIS FOREIGN KEY (PERFIS_ID) REFERENCES PERFIS (ID)
);

INSERT INTO USUARIOS_PERFIS(USUARIOS_ID, PERFIS_ID) VALUES (1,1);
